### ISSUE TITLE
Error due to incomplete code

### ISSUE THREAD

**Issue by Sudershhh** [pranavraikote/CV-Brain-Tumor#1]
Traceback (most recent call last):
  File "C:\Users\tgsud\Desktop\CV-Brain-Tumor-Feature-Extraction-master\Features.py", line 107, in <module>
    d = image_process(i)
  File "C:\Users\tgsud\Desktop\CV-Brain-Tumor-Feature-Extraction-master\Features.py", line 24, in image_process
    _,contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

I'm getting the above error in the findContours line...
Could you tell a way to work around that error?

**Comment by pranavraikote** [comment]
The way to call cv2.findContours is now given as below,
contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

I have updated the code. Thanks for flagging this issue.
